-- +goose Up
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    display_name VARCHAR(120) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT users_username_unique UNIQUE (username),
    CONSTRAINT users_username_length_check
        CHECK (char_length(username) BETWEEN 3 AND 50),
    CONSTRAINT users_username_normalized_check
        CHECK (username = lower(btrim(username))),
    CONSTRAINT users_username_format_check
        CHECK (username ~ '^[a-z0-9][a-z0-9._-]*[a-z0-9]$'),
    CONSTRAINT users_display_name_check
        CHECK (
            display_name = btrim(display_name)
            AND char_length(display_name) BETWEEN 1 AND 120
        ),
    CONSTRAINT users_password_hash_check
        CHECK (char_length(password_hash) BETWEEN 20 AND 255)
);

CREATE TABLE sessions (
    token_hash VARCHAR(64) PRIMARY KEY,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT sessions_token_hash_format_check
        CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT sessions_expiration_check
        CHECK (expires_at > created_at),
    CONSTRAINT sessions_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
);

CREATE TABLE requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
    category VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'aberto',
    requester_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT requests_title_check
        CHECK (
            title = btrim(title)
            AND char_length(title) BETWEEN 3 AND 150
        ),
    CONSTRAINT requests_description_check
        CHECK (
            description = btrim(description)
            AND char_length(description) BETWEEN 10 AND 5000
        ),
    CONSTRAINT requests_category_check
        CHECK (category IN ('ti', 'rh', 'compras', 'financeiro', 'infraestrutura')),
    CONSTRAINT requests_status_check
        CHECK (status IN ('aberto', 'em_atendimento', 'concluido')),
    CONSTRAINT requests_updated_at_check
        CHECK (updated_at >= created_at),
    CONSTRAINT requests_requester_id_fkey
        FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE RESTRICT
);

CREATE INDEX idx_sessions_user_id ON sessions (user_id);
CREATE INDEX idx_sessions_expires_at ON sessions (expires_at);

CREATE INDEX idx_requests_requester_id ON requests (requester_id);
CREATE INDEX idx_requests_status ON requests (status);
CREATE INDEX idx_requests_category ON requests (category);
CREATE INDEX idx_requests_created_at ON requests (created_at DESC);

-- +goose Down
DROP TABLE requests;
DROP TABLE sessions;
DROP TABLE users;

